export const types = {
  FILL_TASKS: 'FILL_TASKS',
  FETCH_TASKS_ASYNC: 'FETCH_TASKS_ASYNC',
  CREATE_TASK: 'CREATE_TASK',
  CREATE_TASK_ASYNC: 'CREATE_TASK_ASYNC',
  REMOVE_TASK: 'REMOVE_TASK',
  REMOVE_TASK_ASYNC: 'REMOVE_TASK_ASYNC',
  UPDATE_TASK: 'UPDATE_TASK',
  UPDATE_TASK_ASYNC: 'UPDATE_TASK_ASYNC',
};