export const types = {
  START_FETCHING: 'START_FETCHING',
  STOP_FETCHING: 'STOP_FETCHING',
  EMIT_ERROR: 'EMIT_ERROR',
  CHECK_CHECKBOX: 'CHECK_CHECKBOX',
  UNCHECK_CHECKBOX: 'UNCHECK_CHECKBOX',
  UPDATE_TASKS_FILTER: 'UPDATE_TASKS_FILTER',
};
